### ISSUE TITLE
NPM site doesn't display README correctly

### ISSUE THREAD

**Issue by danielduan** [npm/www#157]
Not sure if this is the correct place, but I have a private npm site that I publish internal npm packages to. I have a `prepublish` script that generates a list of files included with the package and appends it to the end of my `README.md`. 

something like this (ignore the escape chars):
find *.js files -> sort -> remove slashes -> remove index.js -> print with line numbers
```
find . -type f -name \'*.js\' | sort -f | sed \'s|./||\' | sed \'/index\\.js/d\' | awk \'{printf "%d. `%s`\\n", NR, $0}\' >> README.md
```

The appended list doesn't show up in the README section on the npm site when I run this script during as a prepublish script during `npm publish` but it will show up if I run these commands separately like `append_script_here && npm publish`.

Strange thing is, if I install that published npm module somewhere. The README file would have the appended list in it.

Is there something caching the README file before the `prepublish` stage and is this an intended effect or bug? Thanks!

**Comment by soldair** [comment]
The npm cli reads the readme and holds it in memory before the prepublish hook is run in a step where it builds the metadata. This is the one thats published. I dont think there is another hook you can use that lets you update the readme as you publish. 

Your work around is the current best solution. You could also add a script to your package json like 
 
`"scripts":{"release":append_script_here && npm publish"}`

and instead of running npm publish you could run `npm run release`. 

In the public registry we recently replaced the infrastructure for serving readmes so the version of the readme on the website is the one extracted from the tarball. This fixes your issue also but the process is a little too resource intensive in its current form to port directly to npme. I'm not sure where it is on their roadmap but its on it.

**Comment by danielduan** [comment]
Thanks for the answer, sounds like this was the intended behavor. I'll close this issue.
