### ISSUE TITLE
Session Hijacking

### ISSUE THREAD

**Issue by Sajibekanti** [npm/www#163]
edited by npm.

**Comment by soldair** [comment]
please make security disclosures directly to security@npmjs.com

**Comment by Sajibekanti** [comment]
Hi 
I have report but they havent reply

**Comment by soldair** [comment]
all of out security reports are audited if we havnt replied in a timely manner we either 
- after auditing by our security team have found that the issue does not apply 
- we have not been able to address it yet
- we have not been able to verify that any issue exists before involving security teams and flagged your message as a spam report.

in this particular case its not possible for malicious code or proxies to steal cookies because of https httponly and content security policies. Other mitigations like browser fingerprinting all all fraught and have holes and can be cuircumvented. pinning cookies to ip address also leaves you vulnerable to attacks within your network etc.

if folks share the cookie values they are sharing their login but it should be impossible to do without knowledge of the user.

if you could demonstate a script injection or some other way to cause cookies to be extracted from accounts without using the browser console or other programs on the user machine designed to attack and compromise cookie storage and browser cache that would be amazing and really useful. please email this to security.

thanks for your help.

**Comment by Sajibekanti** [comment]
it possible to Hijack  Cookies:0

**Comment by soldair** [comment]
If so It would be really great if you could make a proof of concept of an exploit so we can understand exactly how  so we can fix it. =) 

When you have it please email security@npmjs.com. you will have our tanks and our users if you  find something. As a security researcher im sure you understand that a public issue tracker isn't the correct place to discuss issues like this.

**Comment by Sajibekanti** [comment]
I have also Added a PoC . 
you Can See 

Thanks
