### ISSUE TITLE
"team" links 404ing

### ISSUE THREAD

**Issue by stephenmathieson** [npm/www#18]
![screen shot 2016-08-15 at 13 55 20](https://cloud.githubusercontent.com/assets/571265/17679380/0a8c301c-62f0-11e6-8982-678a1a52b14d.png)

**Comment by ashleygwilliams** [comment]
hey @stephenmathieson !! thanks for filing, could you include the URL you tried to reach and from what page you tried to reach it! also, in the future, a text version of the error code is very helpful :)

**Comment by stephenmathieson** [comment]
don't have the url still, but it's in the screenshot.

can reproduce by visiting https://www.npmjs.com/org/segment/teams and randomly selecting a team. looks like https://www.npmjs.com/org/segment/team/@segment/api-date-filter_write_2ba6413b-079e-4edf-a09c-ac3a811c3612 is 404ing now

**Comment by ashleygwilliams** [comment]
thanks for the extra info @stephenmathieson !

**Comment by stephenmathieson** [comment]
np!

a bit off topic, but our 1500+ teams also seems like a bug. looks like there was one created for each package? should i file another ticket?

**Comment by ashleygwilliams** [comment]
@stephenmathieson that actually sounds like a support issue, @stephenmathieson -- would you mind emailing support@npmjs.com? i'll ping them now to anticipate your email. they'll be able to help you fix that right away, and also track down what happened. the website just pulls info from our APIs, so that sounds like an issue on the backend. unless of course, you made the teams in the website?

**Comment by jefflembeck** [comment]
hey @stephenmathieson, as I mentioned in the 1500+teams bug, we've heard that Calvin at Segment has spoken with our support team about that issue. These definitely seem related. With that, I'm going to close this issue. If you notice anything funny, please let us know so we can make sure stuff like this doesn't keep happening. We really appreciate the time you took to file these. Thanks!
