### ISSUE TITLE
Incorrect README displayed when GitHub repository linked as homepage

### ISSUE THREAD

**Issue by bhariharan** [npm/www#20]
My package has 2 readme files - one for npm called `npm.md`, and another for my GitHub repository, called `README.md`. When I package my app and publish it, I have a script that renames these readme files, so `npm.md` becomes `README.md` and the original `README.md` becomes `ORIGINAL.md`. npm should display the `README.md` in my package, as opposed to displaying the `README.md` from my GitHub repo, since they're different in this case. This was working correctly until about 6 months ago. My packages where I see this issue are:

- [forcedroid](https://www.npmjs.com/package/forcedroid)
- [forceios](https://www.npmjs.com/package/forceios)

**Comment by bhariharan** [comment]
@ashleygwilliams Do you have an ETA on when this will be fixed? Thanks!

**Comment by aredridel** [comment]
This is a bit tricky: it's not a website bug, since we just display what the registry API gives us.

The registry stores a copy of the README separate from your package contents, and that's what we display. I _think_ (and am confirming right now) that that may vary by `npm` CLI tool version, when it reads and embeds that data into the package metadata at publish time.

For support on an individual basis (rather than bug reporting), you can contact support@npmjs.com and the support team can work to make sure your specific case is taken care of. A broader change will require understanding the bug and use-case and integrating a fix into the appropriate place -- the [registry team's issue tracker](/npm/registry) and [CLI team's](/npm/npm/issues)

**Comment by bhariharan** [comment]
@aredridel Thanks for looking into this. There appears to be no way to explicitly assign a `README` in `package.json`, so if I wanted something like that, I'm guessing I'd have to file an issue with the registry team?

**Comment by bhariharan** [comment]
I filed an issue [here](https://github.com/npm/registry/issues/50).

**Comment by aredridel** [comment]
Yeah, or the CLI team, so that the new README gets packaged up at publish time by `read-package-json`
