### ISSUE TITLE
Npm website does not display correctly on Internet Explorer

### ISSUE THREAD

**Issue by paladox** [npm/www#36]
Hi when I visit https://www.npmjs.com/ this website doesn't display correctly. The logo is misaligned and the login button too. But this displays properly on chrome. I looked on the f12 tools and it shows it is using webkit specific code like -webkit-* which wont work on internet explorer. Please could this be fix?

**Comment by ashleygwilliams** [comment]
hi @paladox! thanks for filing this- and sorry to hear you are dealing with this issue. could you provide some screenshots of this? thanks!

**Comment by paladox** [comment]
Here is how it is displayed in Internet Explorer 11

![screenshot 10](https://cloud.githubusercontent.com/assets/5727000/18974621/0a851b2c-869c-11e6-8000-3bac9919ccc4.png)
![screenshot 11](https://cloud.githubusercontent.com/assets/5727000/18974622/0c6e70b4-869c-11e6-9b73-5f01e8e6b804.png)

And in chrome this is how it is displayed

![screenshot 12](https://cloud.githubusercontent.com/assets/5727000/18974651/3a26bfca-869c-11e6-89ec-f42a7925329d.png)

![screenshot 13](https://cloud.githubusercontent.com/assets/5727000/18974654/401351f0-869c-11e6-9ab2-7951f6341b0d.png)

**Comment by ashleygwilliams** [comment]
got it! thanks for the feedback @paladox - my understanding is now that Edge has been out for a long time now, IE is often not a supported browser (which i believe is the case here, cc/ @jefflembeck ). that being said, if the fix is not too hard, the team *may* take a look and try to fix it, but it likely won't be a priority.

what version of windows are you running? are you able to upgrade your browser? if not, i think the team would be curious to hear the details of a setup that still requires the use of IE (we want everyone to at least have the possibility of a good experience!). thanks again for contributing!

**Comment by paladox** [comment]
I use internet explorer since I have tabs that are important and in edge if it freezes it closes and losses data whereas if it freezes in internet explorer it just waits to unfreeze.

I'm using windows 10.

I'm just used to internet explorer.

**Comment by paladox** [comment]
It is using WebKit specific css property but I'm not sure if it is also js.

**Comment by jefflembeck** [comment]
@paladox it uses webkit-specific css as well as MS-specific css (`display:-ms-flexbox`) as fallbacks for browsers that don't support the proper css for flexbox. What you're seeing is likely due to IE11's issues with bugs in Flexbox.

That being said, this is definitely a bug. I'll take a look to see what I can do.

Thanks for taking the time to submit this.

**Comment by paladox** [comment]
thankyou for looking into this.

**Comment by aredridel** [comment]
This does work in Edge for our info.

**Comment by paladox** [comment]
Thanks.

**Comment by aredridel** [comment]
Sure thing! The update will roll out soon.

**Comment by paladox** [comment]
Ok, thanks :)
