### ISSUE TITLE
fix: stats broken for namespaced packages 

### ISSUE THREAD

**Issue by 3stacks** [npm/www#38]
I've started prefixing my packages with @myName/packageName as suggested in the blog here: http://blog.npmjs.org/post/116936804365/solving-npms-hard-problem-naming-packages.

The problem is that the download stats aren't working on these packages, as confirmed here: https://twitter.com/seldo/status/744418097113636864

Do we have a status update for this?

Thanks all.

**Comment by ashleygwilliams** [comment]
hi @3stacks! thanks for filing. the actual root cause of this issue is with the website backend- so this issue is better filed on the registry public repo: https://github.com/npm/registry

i've copied this issue over there and mentioned you so you can follow the progress. thanks for contributing- feel free to continue the conversation over there :)

https://github.com/npm/registry/issues/59
