### ISSUE TITLE
Feature request: support align attributes on images in markdown readme files

### ISSUE THREAD

**Issue by revelt** [npm/www#51]
Hi all,
You probably noticed that GitHub let's you float images on the README markup documents using `align="left|right"`, but npmjs.com does not. This is counter-intuitive since GitHub doesn't have the sidebar on the right, but npmjs.com does — readme's are even more cramped on this website! Supporting the `align=` attribute on `<img>` tags would relieve this problem.
cheers,
Roy

**Comment by ashleygwilliams** [comment]
hi @revelt ! thanks for filing this. this is actually a feature request for marky-markdown, the npm markdown parser. i've moved the issue over there for you: https://github.com/npm/marky-markdown/issues/269. we care about parity with github and have a new release that is due to come out soon, so hopefully we can take care of this quickly!

**Comment by revelt** [comment]
Awesome! Thanks for fast response. 🦄🦄🦄🌈🌈🌈👍👍👍
