### ISSUE TITLE
Allow search ordering

### ISSUE THREAD

**Issue by adammockor** [npm/www#6]
Allow search ordering based on common criteria such as:
- Number of starts
- Number of downloads
- Recently updated
- ?

**Comment by jefflembeck** [comment]
Hi, thanks for submitting this. We’re currently discussing future plans for search and will get back to you with more information when we know what’s coming down the pipeline.

**Comment by Mithgol** [comment]
+2 criteria:

* number of dependencies

* number of packages that depend on the found package

I believe I would always sort on the latter by default.

**Comment by ESWAT** [comment]
+1 request: the first result, if possible, should be the package with the name that matches the query exactly.

So if my search query is "babel-preset-react", then the `babel-preset-react` package should be the first result returned.

**Comment by dkebler** [comment]
months ago I made an issue about search ordering and filtering....it might have been on the "newww" repo that no longer exists cause I can't find it here.  

Anyway it seems such a request will all be a long time in coming (been a year since I inquired) and like I commented before repos on npm are growing exponentially.  Filtering and ordering down to find something useful is getting to be a requirement, otherwise the whole database becomes kinda useless (I have resorted to searching on github which has slightly better options)

So my question is there a REST or other api to the database?  Is the database mongo?  If the answer is yes to either then can we be provided some information about access.  Then I can just write my own queries as I please....maybe even share if I write a webapp for this.  I recall some time ago somebody had put up an alternative to nmpjs.org site so at least at one time this was possible back with npm 1/2

I understand everyone is time limited all we are asking for is access to a database that seems at least in principle to be public considering it's full of open source code.

**Comment by Mithgol** [comment]
Third-party search interfaces to npm are indeed possible, https://npms.io/ proves it.

**Comment by dkebler** [comment]
@Mithgol , npms.io is a good start and has a published api although I don't see a way to filter on download frequency nor date of last commit nor number of dependencies (which probably just reflects download frequency).  Also corresponding github stars is also another good filter so an API that can access both npm and github dbs would be a winner.  In any respect the code at npms github organization should illuminate access to the npm db.  I'm thinking those here should make feature requests (pull or otherwise) there and maybe @adammockor should just close this.

**Comment by aredridel** [comment]
We've issued an update of search! Check it out!
