### ISSUE TITLE
How to npm install the all dependent moudle of package.json to global env?

### ISSUE THREAD

**Issue by xyy94813** [npm/www#81]
now, I wanna install the all dependent moudle of package.json to global env.

 i try to use 'npm install -g', however it will install my project to global env.

the best result that i hope is only install 'devDepencise' to global env

**Comment by aredridel** [comment]
Is there a reason you are trying to do this? this is not a feature the `npm` command line supports.

Usually you'd want to install your dependencies into your application, so that each application is isolated from others.

Look in the `node_modules/.bin` directory for the scripts those things install -- that can be added to your PATH to run them as part of your project.

This isn't a www issue, so I'm closing the issue. The command line tool's issue tracker is at https://github.com/npm/npm.
