### ISSUE TITLE
Please make the old issues available

### ISSUE THREAD

**Issue by JesseWeinstein** [npm/www#9]
There were over 700 issues in the old repo, including various relevant historical information about the growth and decision-making of npm. It's a shame to have all that historical data made inaccessible. I strongly encourage you to export a copy of it (there are many scripts floating around, I can provide specifics if wanted), and make that available somewhere (either on the npm website, or simply upload it to the Internet Archive as an item).

**Comment by jefflembeck** [comment]
@JesseWeinstein This is a great idea, but is a low priority for us. We’re definitely not opposed, though. If somebody has a script that can help us grab all of the old issues and put them in a file (json works nicely), we’d be happy to put it in here for downloading.

**Comment by JesseWeinstein** [comment]
Great! I can certainly understand it being low priority, and I don't think it's particularly urgent, either -- but I would be glad for it to be done eventually.

Regarding scripts, my first thought is https://github.com/joeyh/github-backup . I haven't used it personally, though, so there may be a better alternative available. I'll ask around.

**Comment by ben-eb** [comment]
Please can you make these available? It's not exactly encouraging to see [threads like these](https://github.com/lerna/lerna/issues/64) lose all context because the issue has been erased. Now, because I don't have a reference of anything in this thread I don't know if this was closed, what priority it had/has, any workarounds, or how many people experienced this issue. It also discourages me from creating a new issue because what's to stop you guys deleting this repository as well and starting over again?

For what it's worth, I'm experiencing this bug still. 😐

**Comment by JesseWeinstein** [comment]
That is a good example of why this is important. It would be most easily solved by just making the repo public again, and adding a prominent notice: "This is for HISTORICAL REFERENCE ONLY." But I suppose there are presumably *some* reasons why that wasn't considered an acceptable solution.

**Comment by JesseWeinstein** [comment]
Also, another possible solution would be to make the repo public again for a short, designated period, and asking the Internet Archive (or ArchiveTeam) to scrape a copy of the issues into the Wayback Machine. Then the repo could be made private again, but the material could still be found at least by those who know to look in the Wayback Machine.
